---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribbble: http://dribbble.com/...
#  license: SIL
#  license_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: shenfei li
  homepage: http://www.qianduan.net
  email: mienflying@gmail.com
  twitter: http://twitter.com/mienflying
  dribbble: http://dribbble.com/mienflying
  github: https://github.com/mienflying/social.logo
  license: SIL
  license_url: http://scripts.sil.org/OFL

  css_prefix: "icon-"
  columns: 4

font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: social

  fullname: social
  familyname: social

  copyright: Copyright (C) 2012 by Daniel Bruce

  ascent: 850
  descent: 150
  weight: Medium


glyphs:

  - css: github
    code: 0xf300
    uid: a9442718c0beb8837757e5c725d2d4de
    search: [github, social, logo]

  - css: github-circled
    code: 0xf301
    uid: 529f41cdc2b32e5e2c138f5a11f530b1
    search: [github, social, logo]

  - css: flickr
    code: 0xf303
    uid: d625b4f2d9e8bc44f44662e6c7502b2c
    search: [flickr, social, logo]

  - css: flickr-circled
    code: 0xf304
    uid: 3f342c647fb0e1ae9089d2126124c2b3
    search: [flickr, social, logo]

  - css: vimeo
    code: 0xf306
    uid: a0651563ec3a1d9f9c9eb768c1eeae6d
    search: [vimeo, social, logo]

  - css: vimeo-circled
    code: 0xf307
    uid: 77b4dddc49ef7035550c33f9b95144dc
    search: [vimeo, social, logo]

  - css: twitter
    code: 0xf309
    uid: ed7f286a79233f34f6d9a9a242bb94f5
    search: [twitter, social, logo]

  - css: twitter-circled
    code: 0xf30a
    uid: a9e8e9c546c2487eb9c033c80de3832d
    search: [twitter, social, logo]

  - css: facebook
    code: 0xf30c
    uid: f220bcc20903090ffe76c6e541d5da6e
    search: [facebook, social, logo]

  - css: facebook-circled
    code: 0xf30d
    uid: 98745ba8e7a5d0f3a11b82ba517bbc95
    search: [facebook, social, logo]

  - css: facebook-squared
    code: 0xf30e
    uid: 1e57ef82ed520373c52bc90976dbf840
    search: [facebook, social, logo]

  - css: gplus
    code: 0xf30f
    uid: 473902f352eefc5e827c58d03515e25c
    search: [google, plus, social, logo]

  - css: gplus-circled
    code: 0xf310
    uid: 26c3302c8405d6306897db381724b63c
    search: [google, plus, social, logo]

  - css: pinterest
    code: 0xf312
    uid: 08c7ca290c5c12708cf04f85546be3e1
    search: [pinterest, social, logo]

  - css: pinterest-circled
    code: 0xf313
    uid: 743cb08680e3d2d3ca13c34de8f978ab
    search: [pinterest, social, logo]

  - css: tumblr
    code: 0xf315
    uid: 43f669b9e1d20f0a6c0fddc8205d3cb0
    search: [tumblr, social, logo]

  - css: tumblr-circled
    code: 0xf316
    uid: 21283447f88d83e313125813a0dcd80c
    search: [tumblr, social, logo]

  - css: linkedin
    code: 0xf318
    uid: be10e7930c8db4400eef837f5d50d021
    search: [linkedin, social, logo]

  - css: linkedin-circled
    code: 0xf319
    uid: d256848c649959a6008bf1d5dd8ae4b7
    search: [linkedin, social, logo]

  - css: dribbble
    code: 0xf31b
    uid: 6cf7d65d00ff6e55ddd2697cc0d198fb
    search: [dribbble, social, logo]

  - css: dribbble-circled
    code: 0xf31c
    uid: 7666dbd40bca3b08f7cd14b7bcc96693
    search: [dribbble, social, logo]

  - css: stumbleupon
    code: 0xf31e
    uid: 25898a85755e74dbda853766d0745225
    search: [stumbleupon, social, logo]

  - css: stumbleupon-circled
    code: 0xf31f
    uid: d951d7602db919844f01c55a499f16b7
    search: [stumbleupon, social, logo]

  - css: lastfm
    code: 0xf321
    uid: 6f75e5aef57cf9c2e4d466ee87f79d4f
    search: [lastfm, social, logo]

  - css: lastfm-circled
    code: 0xf322
    uid: 0f6bf7979de69f6dc98873f805f9f054
    search: [lastfm, social, logo]

  - css: rdio
    code: 0xf324
    uid: 43000bbfc96fcc1da88f0613eb41049f
    search: [rdio, social, logo]

  - css: rdio-circled
    code: 0xf325
    uid: 74c88996168e411280e1c7dc63b18ad7
    search: [rdio, social, logo]

  - css: spotify
    code: 0xf327
    uid: 3a6f131d429577ae9daa07c0546e0739
    search: [spotify, social, logo]

  - css: spotify-circled
    code: 0xf328
    uid: 43b559568fc9472536ac6952c05dbdd0
    search: [spotify, social, logo]

  - css: qq
    code: 0xf32a
    uid: bc60486a3c0ecf674015a81b3b799e1b
    search: [qq, social, logo]

  - css: instagrem
    code: 0xf32d
    uid: 11b214b5aa8b6b45e45820f152dc135e
    search: [instagrem, social, logo]

  - css: dropbox
    code: 0xf330
    uid: d9f59813c92c133a53c8820511099a92
    search: [dropbox, social, logo]

  - css: evernote
    code: 0xf333
    uid: d865f4cb1cfd88e4395cb4425e0d1b66
    search: [evernote, social, logo]

  - css: flattr
    code: 0xf336
    uid: 592608470d3f72b9f483d7897f8fd1ab
    search: [flattr, social, logo]

  - css: skype
    code: 0xf339
    uid: f4c449b549360af43d78341aa35239be
    search: [skype, social, logo]

  - css: skype-circled
    code: 0xf33a
    uid: afc7ad73431e713a20398f57fb190205
    search: [skype, social, logo]

  - css: renren
    code: 0xf33c
    uid: 7fe35dea791456114c356934333b4171
    search: [renren, social, logo]

  - css: sina-weibo
    code: 0xf33f
    uid: ad93d41636e8d79e2c60e1c1364a0231
    search: ['sina-weibo', social, logo]

  - css: paypal
    code: 0xf342
    uid: 13e8423e37c505ccb342ffd949e7f2d6
    search: [paypal, social, logo]

  - css: picasa
    code: 0xf345
    uid: dfffa210196e7cd0651ab0bc216e38e5
    search: [picasa, social, logo]

  - css: soundcloud
    code: 0xf348
    uid: 953408d825a12930de4d70721d215ac5
    search: [soundcloud, social, logo]

  - css: mixi
    code: 0xf34b
    uid: d59ea47547a40691a0232e565c112326
    search: [mixi, social, logo]

  - css: behance
    code: 0xf34e
    uid: 3f1d45d674954bb8ead5fe1e496e2be8
    search: [behance, social, logo]

  - css: google-circles
    code: 0xf351
    uid: d051982c5440efc0becf9c2d04ee6480
    search: [google, circles, social, logo]

  - css: vkontakte
    code: 0xf354
    uid: 827d3f32f51dd7acf314e7eaf712d197
    search: [vkontakte, social, logo]

  - css: smashing
    code: 0xf357
    uid: 047375dab5d3d32e5d886aceb36cba65
    search: [smashing, social, logo]


  -
    css: firefox
    code: 0xe840
    uid: f2d3e2a8edc613bddac152434c3c7719
    meta:
      author: Angela Berbentseva
      email: isux@qq.com
    search: [browser, firefox]
  -
    css: chrome
    code: 0xe841
    uid: 0d354e9826bd616a5a423a3ec2eaf5ee
    meta:
      author: Angela Berbentseva
      email: isux@qq.com
    search: [browser, chrome]
  -
    css: opera
    code: 0xe842
    uid: 085105a45d313ba13547e347ed56c9e1
    meta:
      author: Angela Berbentseva
      email: isux@qq.com
    search: [browser, opera]
  -
    css: ie
    code: 0xe843
    uid: 2d8ed1019c14dfc2c96ee5ae22c40423
    meta:
      author: Angela Berbentseva
      email: isux@qq.com
    search: [browser, ie, bullshit, crap]
