---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribbble: http://dribbble.com/...
#  license: SIL
#  license_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: shenfei li
  homepage: http://www.qianduan.net
  email: mienflying@gmail.com
  twitter: http://twitter.com/mienflying
  dribbble: http://dribbble.com/mienflying
  github: https://github.com/mienflying/social.logo
  license: SIL
  license_url: http://scripts.sil.org/OFL

  css_prefix: "icon-"
  columns: 4

font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: social

  fullname: social
  familyname: social

  copyright: Copyright (C) 2012 by Daniel Bruce

  ascent: 850
  descent: 150
  weight: Medium


glyphs:

  - css: github
    code: 0xf300
    uid: d94334f23acba022bfd68e49d76b31bb
    search: [github, social, logo]

  - css: github-circled
    code: 0xf301
    uid: 91daf8fde1042a363514ca7e42d89570
    search: [github, social, logo]

  - css: flickr
    code: 0xf303
    uid: 14cfd18cc1dd5fb99ba04311b888bc23
    search: [flickr, social, logo]

  - css: flickr-circled
    code: 0xf304
    uid: 5bbd46b2a0b972533f4d3ef243645e1d
    search: [flickr, social, logo]

  - css: vimeo
    code: 0xf306
    uid: 538531af0e023b15882c505ee2297cbe
    search: [vimeo, social, logo]

  - css: vimeo-circled
    code: 0xf307
    uid: 6569bd1801e232180221ba0f6a4b8b27
    search: [vimeo, social, logo]

  - css: twitter
    code: 0xf309
    uid: d090355c31f497b61d676416c1fd39fb
    search: [twitter, social, logo]

  - css: twitter-circled
    code: 0xf30a
    uid: 0419da6446cb4f31093e2022793571ca
    search: [twitter, social, logo]

  - css: facebook
    code: 0xf30c
    uid: bc50457410acf467b8b5721240768742
    search: [facebook, social, logo]

  - css: facebook-circled
    code: 0xf30d
    uid: ce1d525f3f31024c6a6b38f5e9a88953
    search: [facebook, social, logo]

  - css: facebook-squared
    code: 0xf30e
    uid: 47bd87a650e95b97f947d275ed968efe
    search: [facebook, social, logo]

  - css: gplus
    code: 0xf30f
    uid: b945f4ac2439565661e8e4878e35d379
    search: [google, plus, social, logo]

  - css: gplus-circled
    code: 0xf310
    uid: 818a6c2a76c89800632c0335e9cdafee
    search: [google, plus, social, logo]

  - css: pinterest
    code: 0xf312
    uid: 689febe699d74bc8862965555503e445
    search: [pinterest, social, logo]

  - css: pinterest-circled
    code: 0xf313
    uid: 2e9c0fdd4d59598cb122801ab80222e7
    search: [pinterest, social, logo]

  - css: tumblr
    code: 0xf315
    uid: d491462e64eb5b8c4f064108a2ff1780
    search: [tumblr, social, logo]

  - css: tumblr-circled
    code: 0xf316
    uid: 72a6237752f5cd00a107d097adac9ce3
    search: [tumblr, social, logo]

  - css: linkedin
    code: 0xf318
    uid: 7132e1233bc16cd1b6efe7e29d3613a5
    search: [linkedin, social, logo]

  - css: linkedin-circled
    code: 0xf319
    uid: 21adad41ffebf469b2370d26bcb8a3c4
    search: [linkedin, social, logo]

  - css: dribbble
    code: 0xf31b
    uid: e8d13cd05bd63219329b2b61835d776c
    search: [dribbble, social, logo]

  - css: dribbble-circled
    code: 0xf31c
    uid: ec3e0b50a56867ac26a6de47953b9831
    search: [dribbble, social, logo]

  - css: stumbleupon
    code: 0xf31e
    uid: ef5e2b339a93fff038cc6a28f8c91edd
    search: [stumbleupon, social, logo]

  - css: stumbleupon-circled
    code: 0xf31f
    uid: e3606432570e59d4d852727bad063cd1
    search: [stumbleupon, social, logo]

  - css: lastfm
    code: 0xf321
    uid: ae49d5a5d0c2f7253f375bde5f0da2d2
    search: [lastfm, social, logo]

  - css: lastfm-circled
    code: 0xf322
    uid: 9eedcbf6e07d6ba820e3e22f5ab6f734
    search: [lastfm, social, logo]

  - css: rdio
    code: 0xf324
    uid: 406d96226bd9d021b7d976efa1c4a061
    search: [rdio, social, logo]

  - css: rdio-circled
    code: 0xf325
    uid: 4d8e1f1173bab9aac8991e9eee2fa326
    search: [rdio, social, logo]

  - css: spotify
    code: 0xf327
    uid: 882d407598d4e60074f5c08b3372811e
    search: [spotify, social, logo]

  - css: spotify-circled
    code: 0xf328
    uid: 067edf3e1f6458e782d0254e63eb5eb6
    search: [spotify, social, logo]

  - css: qq
    code: 0xf32a
    uid: 935e2e437efbb3a69ed9a83e2d2f637e
    search: [qq, social, logo]

  - css: instagrem
    code: 0xf32d
    uid: 0fbfb1cd7a847c88ea4c141d0e1bbdb5
    search: [instagrem, social, logo]

  - css: dropbox
    code: 0xf330
    uid: b22fdf6cbaa9c54fbb0bc9abb0ed4098
    search: [dropbox, social, logo]

  - css: evernote
    code: 0xf333
    uid: ce291d00162e998dbf5cb81bc5edff75
    search: [evernote, social, logo]

  - css: flattr
    code: 0xf336
    uid: 4274fc9f6190d330fcdf61e7ad564370
    search: [flattr, social, logo]

  - css: skype
    code: 0xf339
    uid: 28ccaf022b8363aeaa5b86f66e1f5173
    search: [skype, social, logo]

  - css: skype-circled
    code: 0xf33a
    uid: 8354734770d837204e6a004885240d2e
    search: [skype, social, logo]

  - css: renren
    code: 0xf33c
    uid: 7fe35dea791456114c356934333b4171
    search: [renren, social, logo]

  - css: sina-weibo
    code: 0xf33f
    uid: d1945696d6bbbf84e388df9961f26a37
    search: ['sina-weibo', social, logo]

  - css: paypal
    code: 0xf342
    uid: 8d584f31a5d54de313f1f3da28708ec0
    search: [paypal, social, logo]

  - css: picasa
    code: 0xf345
    uid: 07269ba9c8905d091e1a01beab1f0958
    search: [picasa, social, logo]

  - css: soundcloud
    code: 0xf348
    uid: b86600decaba538aca184421752cd640
    search: [soundcloud, social, logo]

  - css: mixi
    code: 0xf34b
    uid: c510878e39f27f3fb4e6171148829962
    search: [mixi, social, logo]

  - css: behance
    code: 0xf34e
    uid: 84f3880057574e968053d6d6c8a7b216
    search: [behance, social, logo]

  - css: google-circles
    code: 0xf351
    uid: 5a24a9d2bffe3b66cea31ed2f57fb65a
    search: [google, circles, social, logo]

  - css: vkontakte
    code: 0xf354
    uid: c9a7eca58474311926922ff8c2c1d256
    search: [vkontakte, social, logo]

  - css: smashing
    code: 0xf357
    uid: 2e97984c1130787e123117d4cacc07fa
    search: [smashing, social, logo]


  -
    css: firefox
    code: 0xe840
    uid: 62c089cb34e74b3a1200bc7f5314eb4e
    meta:
      author: Angela Berbentseva
      email: isux@qq.com
    search: [browser, firefox]
  -
    css: chrome
    code: 0xe841
    uid: 9c2b737b16ae2c8d66b7bfd29ba5ecd8
    meta:
      author: Angela Berbentseva
      email: isux@qq.com
    search: [browser, chrome]
  -
    css: opera
    code: 0xe842
    uid: 45861dd1e5ce4fde338bcccf01eeb808
    meta:
      author: Angela Berbentseva
      email: isux@qq.com
    search: [browser, opera]
  -
    css: ie
    code: 0xe843
    uid: 2a46f1d1c9bd036e17a74e46613c1636
    meta:
      author: Angela Berbentseva
      email: isux@qq.com
    search: [browser, ie, bullshit, crap]
